<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;

class HoroscopeAiClient
{
    /**
     * Generate a horoscope payload for a sign and period using Google Gemini.
     *
     * @return array{title:?string, meta_title:?string, meta_description:?string, content_html:?string, love_text:?string, career_text:?string, health_text:?string, money_text:?string, health_percent:?int, occupation_percent:?int, wealth_percent:?int, family_percent:?int, love_life_percent:?int, source:?string, raw:mixed}
     */
    public function generate(string $period, string $sign, string $signLabel): array
    {
        $apiKey = (string) env('GEMINI_API_KEY', '');
        if ($apiKey === '') {
            return [];
        }

        $models = $this->candidateModels();
        $timeout = (int) env('GEMINI_HOROSCOPE_TIMEOUT', 30);
        $brand = (string) config('app.name');

        $instruction = implode("\n", [
            "You are writing horoscope content for {$brand}.",
            "Create a {$period} horoscope for the zodiac sign {$signLabel}.",
            "Return only valid JSON with these keys:",
            "title, meta_title, meta_description, content_html, love_text, career_text, health_text, money_text, health_percent, occupation_percent, wealth_percent, family_percent, love_life_percent",
            "Rules:",
            "- content_html must be a short HTML fragment with 2-4 paragraphs only.",
            "- Each text field should be concise, natural, and original.",
            "- Percent fields must be integers from 0 to 100.",
            "- Do not mention that this was generated by AI.",
            "- Do not include markdown fences or commentary.",
            "- Keep the tone warm, practical, and mystical.",
            "- Tailor the advice specifically to {$signLabel} for the {$period} period.",
        ]);

        foreach ($models as $model) {
            $endpoint = sprintf(
                'https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s',
                rawurlencode($model),
                rawurlencode($apiKey)
            );

            for ($attempt = 1; $attempt <= 3; $attempt++) {
                $resp = Http::timeout($timeout)->post($endpoint, [
                    'contents' => [
                        [
                            'role' => 'user',
                            'parts' => [
                                ['text' => $instruction],
                            ],
                        ],
                    ],
                    'generationConfig' => [
                        'temperature' => 0.8,
                        'maxOutputTokens' => 4096,
                        'responseMimeType' => 'application/json',
                        'responseSchema' => [
                            'type' => 'object',
                            'properties' => [
                                'title' => ['type' => 'string'],
                                'meta_title' => ['type' => 'string'],
                                'meta_description' => ['type' => 'string'],
                                'content_html' => ['type' => 'string'],
                                'love_text' => ['type' => 'string'],
                                'career_text' => ['type' => 'string'],
                                'health_text' => ['type' => 'string'],
                                'money_text' => ['type' => 'string'],
                                'health_percent' => ['type' => 'integer'],
                                'occupation_percent' => ['type' => 'integer'],
                                'wealth_percent' => ['type' => 'integer'],
                                'family_percent' => ['type' => 'integer'],
                                'love_life_percent' => ['type' => 'integer'],
                            ],
                            'required' => [
                                'title',
                                'meta_title',
                                'meta_description',
                                'content_html',
                                'love_text',
                                'career_text',
                                'health_text',
                                'money_text',
                                'health_percent',
                                'occupation_percent',
                                'wealth_percent',
                                'family_percent',
                                'love_life_percent',
                            ],
                        ],
                    ],
                ]);

                if (! $resp->ok()) {
                    $status = $resp->status();
                    if (in_array($status, [429, 500, 502, 503, 504], true) && $attempt < 3) {
                        usleep(250000 * $attempt);
                        continue;
                    }
                    continue 2;
                }

                $json = $resp->json();
                $text = $this->extractText($json);
                if (! is_string($text) || trim($text) === '') {
                    if ($attempt < 3) {
                        usleep(250000 * $attempt);
                        continue;
                    }
                    continue 2;
                }

                $decoded = json_decode($text, true);
                if (! is_array($decoded)) {
                    $jsonText = $this->extractJsonText($text);
                    if (! is_string($jsonText)) {
                        if ($attempt < 3) {
                            usleep(250000 * $attempt);
                            continue;
                        }
                        continue 2;
                    }
                    $decoded = json_decode($jsonText, true);
                    if (! is_array($decoded)) {
                        if ($attempt < 3) {
                            usleep(250000 * $attempt);
                            continue;
                        }
                        continue 2;
                    }
                }

                return [
                    'title' => $this->stringOrNull($decoded['title'] ?? null),
                    'meta_title' => $this->stringOrNull($decoded['meta_title'] ?? null),
                    'meta_description' => $this->stringOrNull($decoded['meta_description'] ?? null),
                    'content_html' => $this->stringOrNull($decoded['content_html'] ?? null),
                    'love_text' => $this->stringOrNull($decoded['love_text'] ?? null),
                    'career_text' => $this->stringOrNull($decoded['career_text'] ?? null),
                    'health_text' => $this->stringOrNull($decoded['health_text'] ?? null),
                    'money_text' => $this->stringOrNull($decoded['money_text'] ?? null),
                    'health_percent' => $this->intOrNull($decoded['health_percent'] ?? null),
                    'occupation_percent' => $this->intOrNull($decoded['occupation_percent'] ?? null),
                    'wealth_percent' => $this->intOrNull($decoded['wealth_percent'] ?? null),
                    'family_percent' => $this->intOrNull($decoded['family_percent'] ?? null),
                    'love_life_percent' => $this->intOrNull($decoded['love_life_percent'] ?? null),
                    'source' => 'gemini:' . $model,
                    'raw' => $json,
                ];
            }
        }

        return [];
    }

    /**
     * @return list<string>
     */
    private function candidateModels(): array
    {
        $configured = trim((string) env('GEMINI_HOROSCOPE_MODEL', 'gemini-3.1-flash-lite'));
        $fallback = trim((string) env('GEMINI_HOROSCOPE_FALLBACK_MODEL', 'gemini-3.1-flash-lite'));

        $models = array_values(array_filter(array_unique([
            $configured,
            $fallback,
            'gemini-3.1-flash-lite',
        ])));

        return $models;
    }

    private function extractJsonText(string $text): ?string
    {
        $text = trim($text);
        if ($text === '') {
            return [];
        }

        if (preg_match('/```(?:json)?\\s*(\\{.*\\})\\s*```/s', $text, $m)) {
            return trim($m[1]);
        }

        if (preg_match('/\\{.*\\}/s', $text, $m)) {
            return trim($m[0]);
        }

        return null;
    }

    private function extractText(mixed $json): ?string
    {
        if (! is_array($json)) {
            return null;
        }

        $candidates = $json['candidates'] ?? null;
        if (! is_array($candidates)) {
            return null;
        }

        foreach ($candidates as $candidate) {
            if (! is_array($candidate)) {
                continue;
            }

            $content = $candidate['content'] ?? null;
            if (! is_array($content)) {
                continue;
            }

            $parts = $content['parts'] ?? null;
            if (! is_array($parts)) {
                continue;
            }

            foreach ($parts as $part) {
                if (is_array($part) && isset($part['text']) && is_string($part['text'])) {
                    return trim($part['text']);
                }
            }
        }

        return null;
    }

    private function stringOrNull(mixed $value): ?string
    {
        if (! is_string($value)) {
            return null;
        }

        $value = trim($value);
        return $value === '' ? null : $value;
    }

    private function intOrNull(mixed $value): ?int
    {
        if (is_int($value)) {
            return max(0, min(100, $value));
        }
        if (is_numeric($value)) {
            return max(0, min(100, (int) $value));
        }

        return null;
    }
}
